# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5005bc9c1c65e4ba283e45e76467b0df97c9986101e4349088b916c80b3b8166201bb97510d97edd51a2136a6f60aa5325b25afb5e8d02f10ed0c36bc5c2a1b

test:
  secret_key_base: 20409a8c43bc17a99a58af5df5411cb6e26ac8ded5671750b86cabf6637524a55bde0ed09a5595132e2af60b8d3ca1a1009e532b2fcf0d7cb0451d895f72ff1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
